#!/usr/bin/env bash

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# ensure no surprises from binder's "half" activation
source activate ${NB_PYTHON_PREFIX}

# use strict and verbose shell settings
set -euxo pipefail


# Build and install ipykernel jep91 branch
pip list | grep ipykernel

git clone --depth 1 --single-branch --branch jep91 https://github.com/ianthomas23/ipykernel
cd ipykernel
git branch
pip install -v .
cd ..
rm -rf ipykernel

pip list | grep ipykernel


# create log folder, named to appear at the top of the file browser
#mkdir _reports_

# pre-install nodejs deps and build outside of editable python install
(time yarn)
(time yarn build:dev:prod)
#(time yarn build:dev:prod:minimize:report)             2>&1 | tee _reports_/01_build.txt

# hoist report to where a reviewer might see it
#mv dev_mode/static/webpack-bundle-analyzer.html _reports_/

# overload best-effort versions from conda-forge for all deps
(time pip install -v -e .[dev] --no-build-isolation)

# copy configuration to well-known location
mkdir -p ~/.jupyter
cp binder/jupyter_config.py ~/.jupyter/

# capture configuration and debug information
(time pip list)
(time pip check || echo FAIL)
(time jupyter troubleshoot)
(time jupyter notebook --show-config)
(time jupyter lab --show-config)
(time jupyter server extension list)
(time jupyter labextension list)

# clean up egregious wastes of space
rm -rf \
    ~/.cache \
    dev_mode/stats.json \
    node_modules/@stdlib
